CREATE DATABASE ParkingMeterDB;
GO

USE ParkingMeterDB;
GO

-- Parking_Management_District Table
CREATE TABLE Parking_Management_District (
    PM_DISTRICT_ID INT PRIMARY KEY,
    District_Name NVARCHAR(255) NULL
);

-- Parking_Space Table
CREATE TABLE Parking_Space (
    PARKING_SPACE_ID INT PRIMARY KEY,
    Location_Description NVARCHAR(255) NULL,
    Space_Type NVARCHAR(50) NULL
);

-- Street Table
CREATE TABLE Street (
    STREET_ID INT PRIMARY KEY,
    STREET_NAME NVARCHAR(255) NOT NULL,
    STREET_SEG_CTRLN_ID INT NULL,
    ORIENTATION NVARCHAR(50) NULL
);

-- Off_Street_Parking Table
CREATE TABLE Off_Street_Parking (
    OSP_ID INT PRIMARY KEY,
    Name NVARCHAR(255) NULL,
    Location NVARCHAR(255) NULL
);

-- Parking_Meter Table
CREATE TABLE Parking_Meter (
    OBJECTID INT PRIMARY KEY,
    PM_DISTRICT_ID INT NULL,
    BLOCKFACE_ID INT NULL,
    ACTIVE_METER_FLAG CHAR(1) NULL,
    REASON_CODE NVARCHAR(50) NULL,
    SMART_METER_FLAG NVARCHAR(50) NULL,
    METER_TYPE NVARCHAR(10) NULL,
    METER_VENDOR NVARCHAR(255) NULL,
    METER_MODEL NVARCHAR(255) NULL,
    CAP_COLOR NVARCHAR(50) NULL,
    PCO_BEAT NVARCHAR(50) NULL,
    PARKING_SPACE_ID INT NULL,
    OLD_RATE_AREA NVARCHAR(50) NULL,
    STREET_ID INT NULL,
    STREET_NAME NVARCHAR(255) NOT NULL,
    STREET_NUM INT NULL,
    PARITY_DIGIT_POSITION NVARCHAR(50) NULL,
    STREET_SEG_CTRLN_ID INT NULL,
    ORIENTATION NVARCHAR(50) NULL,
    LONGITUDE FLOAT NULL,
    LATITUDE FLOAT NULL,
    LEGISLATION_REF NVARCHAR(255) NULL,
    POST_ID NVARCHAR(255) NULL,
    LEGISLATION_DT NVARCHAR(50) NULL,
    WORK_ORDER NVARCHAR(50) NULL,
    COMMENTS NVARCHAR(MAX) NULL,
    COLLECTION_ROUTE NVARCHAR(50) NULL,
    COLLECTION_SUBROUTE NVARCHAR(50) NULL,
    PMR_ROUTE NVARCHAR(50) NULL,
    MS_PAY_STATION_ID NVARCHAR(50) NULL,
    NFC_KEY NVARCHAR(50) NULL,
    SPT_CODE NVARCHAR(50) NULL,
    COLLECTION_ROUTE_DESC NVARCHAR(255) NULL,
    COLLECTION_SUBROUTE_DESC NVARCHAR(255) NULL,
    SHAPE NVARCHAR(255) NULL,
    DATA_AS_OF DATETIME NULL,
    MS_SPACE_NUM INT NULL,
    DATA_LOADED_AT DATETIME NULL,
    ANALYSIS_NEIGHBORHOOD NVARCHAR(255) NULL,
    SUPERVISOR_DISTRICT NVARCHAR(50) NULL,
    SENSOR_FLAG NVARCHAR(10) NULL,
    ON_OFFSTREET_TYPE NVARCHAR(50) NULL,
    OSP_ID INT NULL,
    JURISDICTION NVARCHAR(255) NULL,
    CONSTRAINT FK_PM_DISTRICT FOREIGN KEY (PM_DISTRICT_ID) REFERENCES Parking_Management_District(PM_DISTRICT_ID),
    CONSTRAINT FK_PARKING_SPACE FOREIGN KEY (PARKING_SPACE_ID) REFERENCES Parking_Space(PARKING_SPACE_ID),
    CONSTRAINT FK_STREET FOREIGN KEY (STREET_ID) REFERENCES Street(STREET_ID),
    CONSTRAINT FK_OFF_STREET_PARKING FOREIGN KEY (OSP_ID) REFERENCES Off_Street_Parking(OSP_ID)
);
GO
